#+title:⚡ Flash Coffee Completions
Sponsored by: Ewaldo Samuel Flash Coffee Account
url menu: https://flash-coffee.com/id/menu/
* Menu [11/47]
- [ ] Americano
- [ ] Aren Frappe
- [ ] Avo Choco Shake
- [ ] Avo Latte
- [ ] Black Rock
- [X] Buttery Iftar Shake 9/10 - Creamy & savory, personal favorite. Tapi not for all.
- [ ] Cappuccino
- [X] Caramel Latte 7.5/10 - Enak, kalau bingung mau mesen apa tinggal pilih ini.
- [X] Charcoal Latte 6/10 - Rasanya ga ada beda sama latte plain.
- [ ] Choco Bliss
- [ ] Choco Caramel Latte with Oatmilk
- [ ] Choco Fudge Frappe
- [ ] Choco Hazelnut Frappe
- [ ] Chocolate Hazelnut Latte
- [ ] Chocolate Hazelnut Shake
- [ ] Chocomint Shake with Oatmilk
- [ ] Clean Ice Tea
- [ ] Coconut Latte
- [ ] Coconut Matcha Shake
- [ ] Coconut Oreo Shake
- [ ] Espresso
- [ ] Flash Chocolate
- [ ] Latte Gula Aren
- [ ] Latte Gula Aren with Almond Milk
- [ ] Lemon Ice Tea
- [ ] Lychee Ice Tea
- [ ] Macadamia Frappe
- [X] Macadamia Latte 8/10 - Pesanan default kalau gtw mau beli apa, enak.
- [ ] Matcha Frappe
- [X] Matcha Latte 7/10 - Matchanya kerasa, ga terlalu essence rasanya. Jadi kalau yang suka matcha bakal lebih preferable daripada yang plain, tapi not as good as macadamia.
- [ ] Matcha Macadamia Shake
- [ ] Mocha Latte
- [ ] Oatmilk Cappuccino
- [ ] Oatmilk Latte
- [ ] Oreo Cookies Cream Frappe
- [ ] Oreo Shake
- [ ] Pretea Girl
- [X] Sparkling Espresso 1/10 - No, just no
- [X] Sparkling Espresso with Lemon Flavor n/10 - yg original aja udh disgusting
- [X] Sparkling Espresso with Lychee Flavor n/10 - gamau, sayang duit
- [ ] Strawberry Ice Tea
- [X] Strawberry Latte 3/10 - Strawberrynya aneh rasanya, kayak "keset". Tapi sesudah beberapa kl minum, not bad sih.
- [ ] Strawberry Shake
- [ ] Thai tea
- [X] Toblerone Latte 6/10 - Beneran latte normal, dicelupin toblerone. Not worth
- [ ] Vanilla Ice Tea
- [X] Vanilla Latte 8/10 - Better than caramel latte, hampir mendekati macadamia. Overall enak, kalau males mikir boleh ini.
